_index:
    path:     /
    defaults: { _controller: "ShowcaseBundle:Article:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "ShowcaseBundle:Article:show" }
    methods:  GET

#_new:
#    path:     /new
#    defaults: { _controller: "ShowcaseBundle:Article:new" }
#    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShowcaseBundle:Article:edit" }
    methods:  [GET, POST]

_filter_category:
    path:     /{category}
    defaults: { _controller: "ShowcaseBundle:Article:filterCategory" }
    methods:  GET

#_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "ShowcaseBundle:Article:delete" }
#    methods:  DELETE
